version: '3'
services:
  app:
    container_name: alura
    image: ambientum/php:7.4-nginx
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/app
    depends_on:
        - mysql
    environment:
        - MYSQL_USER=doctor
        - MYSQL_PASS=123456
  composer:
    image: composer/composer
    ports:
        - "8081:8080"
    volumes:
        - ".:/composer"
    container_name: composer
    working_dir: /composer
    command: install
  mysql:
    image: mysql:8.0.23
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mysql/initial_data:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456

volumes:
  db_data:
